var docProfileData = {
	
	fName : 'Shyam',
	mName : 'Kumar',
	lName : 'K G',
	rating : 3.5,
	no_of_reviews : 27,
	practiceSinceYear : 1947,
	degrees : 'MBBS, MD',
	dob : new Date(),
	addr1 : '#25, 2nd Floor',
	addr2 : 'Ayodhya Nagar, J.P 5th Phase',
	city : 'Bangalore',
	state : 'Karnataka',
	emailId : 'shyam@gmail.com',
	mobileNum : '9980518849',
	knownLanguages : 'Marathi, Kannada, Telugu, English',
	bankName : 'SBI',
	acctNum : '201237878754',
	ifscCode : 'SBIN004987',
	feesDesired : 400,
	specialist : 'Dermatologist',
	membership : 'Not Available',
	membershipNum : 456
}